# Generated by Django 2.0 on 2021-05-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteGerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', editable=False, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('data', models.CharField(max_length=250)),
                ('precoUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('data', models.CharField(max_length=250)),
                ('precoUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=250)),
                ('quantidade', models.FloatField()),
                ('precoUnitario', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='clienteCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='ativo',
            name='dataCriacao',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ativo'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='codigoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ativo'),
        ),
        migrations.AddField(
            model_name='retirada',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ativo'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ativo'),
        ),
        migrations.AddField(
            model_name='clientegerente',
            name='codigoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='clienteCriador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ClienteGerente'),
            preserve_default=False,
        ),
    ]
